version: '3'
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS:=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes 
    depends_on:
      - zookeeper
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sa2
      MYSQL_USER: omar
      MYSQL_PASSWORD: 123
    ports:
      - 3306:3306
    
  consumer:
    image: sa2-project/customer
    environment:
      DB_HOST: db
      KAFKA_HOST: kafka:9092
    ports:
      - 5002:5002 
    depends_on:
      - db
  marketer:
    image: sa2-project/marketer
    environment:
      KAFKA_HOST: kafka:9092
    ports:
      - 8080:8080
 